# SUPPORT : {PLAYER} {REMAINING}
items:
  minecraft:stick:
    cooldown: 30
    message: "§cVous êtes encore en cooldown pendant {REMAINING} secondes"
  minecraft:slimeball:
    cooldown: 60
    message: "§cVous êtes encore en cooldown pendant {REMAINING} secondes"

